# -*- coding: utf-8 -*-
"""Perpustakaan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-xhIBsg98pVnF25PF7zK-NB2cwjeLtw
"""

listPerpustakaan = [
     {
        'JudulBuku' : 'Pemrograman WEB Pemula',
        'JumlahBuku' : 2,
        'HargaPeminjaman' : 10000,
        'KodeBuku' : 122
    },
    {
        'JudulBuku' : 'Dasar Belajar Science ',
        'JumlahBuku' : 4,
        'HargaPeminjaman' : 12000,
        'KodeBuku' : 444
    },
    {
        'JudulBuku' : 'Data Science Fundamental',
        'JumlahBuku' : 3,
        'HargaPeminjaman' : 15000,
        'KodeBuku' : 111
    },
    {
        'JudulBuku' : 'Pengenalan Ilmu Informatika',
        'JumlahBuku' : 5,
        'HargaPeminjaman' : 17000,
        'KodeBuku' : 222
    },
    {
        'JudulBuku' : 'Informatika Untuk Masyarakat',
        'JumlahBuku' : 7,
        'HargaPeminjaman' : 20000,
        'KodeBuku' : 333
    }
]

def show_data():
  if(len(listPerpustakaan)<=0):
    print("belum ada buku")
  else:
    print('=============================================================================')
    print('                               Daftar Buku                                   ')
    print('=============================================================================')
    print('No\t | Judul Buku               \t | Jumlah Buku\t | Kode Buku | Harga Peminjaman | ')
    for i in range(len(listPerpustakaan)) :
      print('{}\t | {}\t | {}          \t | {} | {}            |'. format(i,listPerpustakaan[i]['JudulBuku'],listPerpustakaan[i]['JumlahBuku'],listPerpustakaan[i]['KodeBuku'],listPerpustakaan[i]['HargaPeminjaman']))

def CariKode():
  cari = int(input('Masukkan Kode Buku Yang ingin Dicari : '))
  for i in range(len(listPerpustakaan)):
    x = listPerpustakaan[i]['KodeBuku']
    if x == cari :
      return i
  return -1

def PilihKode():
  temp = CariKode()
  if (temp == -1):
    print('Data Tidak ada')
  else:
    # print(listPerpustakaan[temp])
    print('=============================================================================')
    print('                               Buku Yang Dicari                              ')
    print('=============================================================================')
    print('{}\t | {}\t | {}          \t | {} | {}            |'. format(temp,listPerpustakaan[temp]['JudulBuku'],listPerpustakaan[temp]['JumlahBuku'],listPerpustakaan[temp]['KodeBuku'],listPerpustakaan[temp]['HargaPeminjaman']))


def TampilanReadData():
  while True:
    print(" ")
    print("|===================================================|")
    print("|           INI ADALAH HALAMAN READ DATA            |")
    print("|===================================================|")
    print("|              1. Tampilin Semua Data               |")
    print("|              2. Pilih Berdasar Kode Buku          |")
    print("|                  3. Keluar                        |")
    print("|===================================================|")
    print("|         Silahkan Pilih Nomor Yang Tersedia        |")
    print("|===================================================|")
    pilih = int(input('Pilih No 1-3 : '))
    try:
      if (pilih == 1):
        show_data()
        continue
      elif(pilih == 2):
        PilihKode()
        continue
      elif(pilih == 3):
        MainMenu()
        break
      else:
        print("Masukkan Angka 1-2")
        continue
    except ValueError:
      print("Masukkan Sesuai Petunjuk Yang Ada")

def cari_data(x):
  temp = False
  for i in range(len(listPerpustakaan)):
    j=(listPerpustakaan[i]['KodeBuku'])
    if(x==j):
      temp=True
  return temp

def CreateData():
    x = int(input('masukan kode buku:'))
    k = cari_data(x)
    print('cari data hasil',k)
    if(k==True):
      print('data duplikat tidak bisa input')
    else:
      Judul_Buku = input('Masukkan Judul Buku : ')
      Jumlah_Buku = input('Masukkan Jumlah Buku : ')
      Harga_Peminjaman = int(input('Masukkan Harga Peminjaman Buku : '))
      cek = input('Yakin Ingin Membuat Data? (y/t) : ')
      if cek == 'y':
        listPerpustakaan.append({
          'JudulBuku' : Judul_Buku,
          'JumlahBuku' : Jumlah_Buku,
          'HargaPeminjaman' : Harga_Peminjaman,
          'KodeBuku' : x
        })
        print('Data Berhasil Dibuat')
        show_data()
      else:
        print('Gagal Membuat Data')
        TampilanCreateData()

def TampilanCreateData():
  while True:
    print(" ")
    print("|===================================================|")
    print("|          INI ADALAH HALAMAN CREATE DATA           |")
    print("|===================================================|")
    print("|              1. Membuat Data                      |")
    print("|              2. Keluar                            |")
    print("|===================================================|")
    print("|         Silahkan Pilih Nomor Yang Tersedia        |")
    print("|===================================================|")
    x = int(input("pilih no 1-2 : "))
    try:
      if(x==1):
        CreateData()
        continue
      elif(x==2):
        MainMenu()
        break
      else:
        print("Masukkan Angka 1-2")
        continue
    except ValueError:
      print("Masukkan Sesuai Petunjuk Yang Ada")

def TampilanUpdate():
  while True:
    print(" ")
    print("|===================================================|")
    print("|         INI ADALAH HALAMAN UPDATE DATA            |")
    print("|===================================================|")
    print("|              1. Update Data                       |")
    print("|              2. Keluar                            |")
    print("|===================================================|")
    print("|         Silahkan Pilih Nomor Yang Tersedia        |")
    print("|===================================================|")
    x = int(input("pilih no 1-2 : "))
    try:
      if(x==1):
        update_data()
        continue
      elif(x==2):
        MainMenu()
        break
      else:
        print("Masukkan Angka 1-2")
        continue
    except ValueError:
      print("Masukkan Sesuai Petunjuk Yang Ada")

def update_data():
    show_data()
    indeks = int(input("inputkan Index buku: "))
    if(indeks > len(listPerpustakaan)):
        print("index Salah")
    else:
        judul_baru = input("Judul Baru : ")
        listPerpustakaan[indeks]['JudulBuku'] = judul_baru
        jumlah_baru = input("Jumlah Buku : ")
        listPerpustakaan[indeks]['JumlahBuku'] = jumlah_baru
        harga_baru = input("Harga Peminjaman : ")
        listPerpustakaan[indeks]['HargaPeminjaman'] = harga_baru
        kode_baru = input("Kode Buku : ")
        listPerpustakaan[indeks]['KodeBuku'] = kode_baru
        cek = input("Yakin Ingin Mengupdate Buku?(y/t) : ")
        if cek == 'y':
          print("Berhasil Update Data")
          show_data()
        else:
          print("Gagal Update Data")
          TampilanUpdate()

def TampilanDelete():
  while True:
    print(" ")
    print("|===================================================|")
    print("|         INI ADALAH HALAMAN DELETE DATA            |")
    print("|===================================================|")
    print("|              1. Delete Data                       |")
    print("|              2. Keluar                            |")
    print("|===================================================|")
    print("|         Silahkan Pilih Nomor Yang Tersedia        |")
    print("|===================================================|")
    x = int(input("pilih no 1-2 : "))
    try:
      if(x==1):
        hapus_data()
        continue
      elif(x==2):
        MainMenu()
        break
      else:
        print("Masukkan Angka 1-2")
        continue
    except ValueError:
      print("Masukkan Sesuai Petunjuk Yang Ada")

def hapus_data():
    show_data()
    indeks = int(input("masukan Index Buku: "))
    if(indeks > len(listPerpustakaan)):
        print("Index Salah")
    else:
      cek = input("Apakah Yakin Ingin Delete Data?(y/t) : ")
      if cek == 'y':
        listPerpustakaan.remove(listPerpustakaan[indeks])
        print("Data Berhasil Dihapus")
        show_data()
      else:
        print("Data Gagal Dihapus")
        TampilanDelete()

def MainMenu():

    print(" ")
    print("|===================================================|")
    print("|Selamat Datang Pada Halaman Menu Admin Perpustakaan|")
    print("|===================================================|")
    print("|                  1. Read Data                     |")
    print("|                  2. Create Data                   |")
    print("|                  3. Update Data                   |")
    print("|                  4. Delete Data                   |")
    print("|                  5. Keluar                        |")
    print("|===================================================|")
    print("|         Silahkan Pilih Nomor Yang Tersedia        |")
    print("|===================================================|")

    pilih=int(input("pilih menu 1-5: "))
    print()
    if(pilih==1):
        TampilanReadData()
    elif(pilih==2):
        TampilanCreateData()
    elif(pilih==3):
        TampilanUpdate()
    elif(pilih==4):
        TampilanDelete()  
    elif(pilih==5):
        print("Terimakasih telah menggunakan sistem perpustakaan")
        exit()
    else:
      print("masukkan sesuai petunjuk !")
          
    #         print(ppp)
    #         break
    #     else:
    #         print("Masukkan angka 1-5")
    #         continue
    # except ValueError:
    #     print("masukkan sesuai petunjuk !")
    #     continue

MainMenu()